https://blog.csdn.net/liuxiao214/article/details/81037416

In [1]:
import os 
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import tensorflow as tf
import numpy as np


from tensorflow.keras.layers import LeakyReLU, ReLU, LayerNormalization,BatchNormalization


In [29]:
tf.keras.backend.set_floatx('float64')

In [48]:
a = np.arange(1, 10)
x = np.ones((9,9))
for i in range(9):
    x[i] = a
x = x.astype('float64')
print(x)
x = x.reshape(1, 9, 9)

[[1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]]


In [57]:
res = BatchNormalization(axis=2)(x).numpy()

In [58]:
res

array([[[0.99950037, 1.99900075, 2.99850112, 3.9980015 , 4.99750187,
         5.99700225, 6.99650262, 7.996003  , 8.99550337],
        [0.99950037, 1.99900075, 2.99850112, 3.9980015 , 4.99750187,
         5.99700225, 6.99650262, 7.996003  , 8.99550337],
        [0.99950037, 1.99900075, 2.99850112, 3.9980015 , 4.99750187,
         5.99700225, 6.99650262, 7.996003  , 8.99550337],
        [0.99950037, 1.99900075, 2.99850112, 3.9980015 , 4.99750187,
         5.99700225, 6.99650262, 7.996003  , 8.99550337],
        [0.99950037, 1.99900075, 2.99850112, 3.9980015 , 4.99750187,
         5.99700225, 6.99650262, 7.996003  , 8.99550337],
        [0.99950037, 1.99900075, 2.99850112, 3.9980015 , 4.99750187,
         5.99700225, 6.99650262, 7.996003  , 8.99550337],
        [0.99950037, 1.99900075, 2.99850112, 3.9980015 , 4.99750187,
         5.99700225, 6.99650262, 7.996003  , 8.99550337],
        [0.99950037, 1.99900075, 2.99850112, 3.9980015 , 4.99750187,
         5.99700225, 6.99650262, 7.996003 

In [61]:
res = LayerNormalization(axis=2)(x).numpy()
res

array([[[-1.54907716, -1.16180787, -0.77453858, -0.38726929,
          0.        ,  0.38726929,  0.77453858,  1.16180787,
          1.54907716],
        [-1.54907716, -1.16180787, -0.77453858, -0.38726929,
          0.        ,  0.38726929,  0.77453858,  1.16180787,
          1.54907716],
        [-1.54907716, -1.16180787, -0.77453858, -0.38726929,
          0.        ,  0.38726929,  0.77453858,  1.16180787,
          1.54907716],
        [-1.54907716, -1.16180787, -0.77453858, -0.38726929,
          0.        ,  0.38726929,  0.77453858,  1.16180787,
          1.54907716],
        [-1.54907716, -1.16180787, -0.77453858, -0.38726929,
          0.        ,  0.38726929,  0.77453858,  1.16180787,
          1.54907716],
        [-1.54907716, -1.16180787, -0.77453858, -0.38726929,
          0.        ,  0.38726929,  0.77453858,  1.16180787,
          1.54907716],
        [-1.54907716, -1.16180787, -0.77453858, -0.38726929,
          0.        ,  0.38726929,  0.77453858,  1.16180787,
        

In [46]:
res

array([[-1.54907716, -1.16180787, -0.77453858, -0.38726929,  0.        ,
         0.38726929,  0.77453858,  1.16180787,  1.54907716],
       [-1.54907716, -1.16180787, -0.77453858, -0.38726929,  0.        ,
         0.38726929,  0.77453858,  1.16180787,  1.54907716],
       [-1.54907716, -1.16180787, -0.77453858, -0.38726929,  0.        ,
         0.38726929,  0.77453858,  1.16180787,  1.54907716],
       [-1.54907716, -1.16180787, -0.77453858, -0.38726929,  0.        ,
         0.38726929,  0.77453858,  1.16180787,  1.54907716],
       [-1.54907716, -1.16180787, -0.77453858, -0.38726929,  0.        ,
         0.38726929,  0.77453858,  1.16180787,  1.54907716],
       [-1.54907716, -1.16180787, -0.77453858, -0.38726929,  0.        ,
         0.38726929,  0.77453858,  1.16180787,  1.54907716],
       [-1.54907716, -1.16180787, -0.77453858, -0.38726929,  0.        ,
         0.38726929,  0.77453858,  1.16180787,  1.54907716],
       [-1.54907716, -1.16180787, -0.77453858, -0.38726929,  0